<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create your Amazon account</name>
   <tag></tag>
   <elementGuidId>ae8cadee-d0b2-476a-8ee9-4cca4daf024e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-create-account-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='auth-create-account-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5e84c278-2f0d-4273-811b-b9e60f39b7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-create-account-link</value>
      <webElementGuid>fcf732a6-f17a-4192-8625-e2a5ccce9fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-span12 a-button-base</value>
      <webElementGuid>7908a410-dd25-45a4-8702-2bd1b67eeb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Create your Amazon account
        </value>
      <webElementGuid>f8dbb122-5c73-48a4-9393-d62890c4c792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-create-account-link&quot;)</value>
      <webElementGuid>ee6ce5de-620b-4f4d-81ef-24bf4b19818e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='auth-create-account-link']</value>
      <webElementGuid>59a71d5f-038d-4fe1-87b2-9112096eeede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div[2]/span</value>
      <webElementGuid>8ef71f02-719d-4eca-9383-29a23e69d0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>217b6205-4f1b-4c01-af33-6516b77b9e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'auth-create-account-link' and (text() = '
          Create your Amazon account
        ' or . = '
          Create your Amazon account
        ')]</value>
      <webElementGuid>85c2f38a-3a0e-4434-9d65-2137a592d4cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
